class Keyb < Formula
  desc "Echoes individual bytes generated by keystrokes"
  homepage "https://github.com/davidledwards/keyb"
  url "https://github.com/davidledwards/keyb/releases/download/v0.1.0/keyb-0.1.0-x86_64-unix.tar.gz"
  sha256 "28dd6467bcbf4dd3ed2a1cb05ec4e6eeff443e1719fcf1faeb40ad3c1bcc33e7"
  version "0.1.0"

  def install
    bin.install "keyb"
  end
end
