class Keyb < Formula
  desc "Echoes individual bytes generated by keystrokes"
  homepage "https://github.com/davidledwards/keyb"
  version "0.2.0"

  if OS.linux? || OS.mac?
    if Hardware::CPU.intel?
      url "https://github.com/davidledwards/keyb/releases/download/v" + version + "/keyb-" + version + "-x86_64-unix.tar.gz"
      sha256 "a93e24bdda12d308a166d30f341896cf015477b9b1924000d2fad951b8f7ad7c"
    elsif Hardware::CPU::arm?
      url "https://github.com/davidledwards/keyb/releases/download/v" + version + "/keyb-" + version + "-aarch64-unix.tar.gz"
      sha256 "3077885ae2698619650363753e1d6e5238f45d4465c9dcfe839579f14ea762c4"
    end
  end

  def install
    bin.install "keyb"
  end
end
