class Keyb < Formula
  desc "Echoes individual bytes generated by keystrokes"
  homepage "https://github.com/davidledwards/keyb"
  version "0.3.1"

  if OS.linux? || OS.mac?
    if Hardware::CPU.intel?
      url "https://github.com/davidledwards/keyb/releases/download/v" + version + "/keyb-" + version + "-x86_64-unix.tar.gz"
      sha256 "548d039ed0289953395aa7168470098786d0c83dbe22eab79393cd6c47a31465"
    elsif Hardware::CPU::arm?
      url "https://github.com/davidledwards/keyb/releases/download/v" + version + "/keyb-" + version + "-aarch64-unix.tar.gz"
      sha256 "e6370d9e79b1e1bcbab8925a1e27eca8f002a1ed8dd68cc8f305637dfd351e17"
    end
  end

  def install
    bin.install "keyb"
  end
end
